// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-data-srv.proto

package user_data_srv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//AddUser Function
type UserData struct {
	Data                 map[string]string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Error                string            `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_504ce8545baed7b1, []int{0}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserData) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type AddUserResponse struct {
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserResponse) Reset()         { *m = AddUserResponse{} }
func (m *AddUserResponse) String() string { return proto.CompactTextString(m) }
func (*AddUserResponse) ProtoMessage()    {}
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_504ce8545baed7b1, []int{1}
}

func (m *AddUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserResponse.Unmarshal(m, b)
}
func (m *AddUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserResponse.Marshal(b, m, deterministic)
}
func (m *AddUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserResponse.Merge(m, src)
}
func (m *AddUserResponse) XXX_Size() int {
	return xxx_messageInfo_AddUserResponse.Size(m)
}
func (m *AddUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserResponse proto.InternalMessageInfo

func (m *AddUserResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *AddUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

//GetUser Function
type GetUserRequest struct {
	UserID               string   `protobuf:"bytes,9,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_504ce8545baed7b1, []int{2}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

//GetUserIDByUsername Function
type GetUserByUsernameOrEmailRequest struct {
	Username             string   `protobuf:"bytes,10,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,11,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByUsernameOrEmailRequest) Reset()         { *m = GetUserByUsernameOrEmailRequest{} }
func (m *GetUserByUsernameOrEmailRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByUsernameOrEmailRequest) ProtoMessage()    {}
func (*GetUserByUsernameOrEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_504ce8545baed7b1, []int{3}
}

func (m *GetUserByUsernameOrEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByUsernameOrEmailRequest.Unmarshal(m, b)
}
func (m *GetUserByUsernameOrEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByUsernameOrEmailRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByUsernameOrEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByUsernameOrEmailRequest.Merge(m, src)
}
func (m *GetUserByUsernameOrEmailRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByUsernameOrEmailRequest.Size(m)
}
func (m *GetUserByUsernameOrEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByUsernameOrEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByUsernameOrEmailRequest proto.InternalMessageInfo

func (m *GetUserByUsernameOrEmailRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUserByUsernameOrEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

//Auth User Function
type AuthUserRequest struct {
	Username             string   `protobuf:"bytes,14,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,15,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,16,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthUserRequest) Reset()         { *m = AuthUserRequest{} }
func (m *AuthUserRequest) String() string { return proto.CompactTextString(m) }
func (*AuthUserRequest) ProtoMessage()    {}
func (*AuthUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_504ce8545baed7b1, []int{4}
}

func (m *AuthUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthUserRequest.Unmarshal(m, b)
}
func (m *AuthUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthUserRequest.Marshal(b, m, deterministic)
}
func (m *AuthUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthUserRequest.Merge(m, src)
}
func (m *AuthUserRequest) XXX_Size() int {
	return xxx_messageInfo_AuthUserRequest.Size(m)
}
func (m *AuthUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthUserRequest proto.InternalMessageInfo

func (m *AuthUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthUserResponse struct {
	Valid                bool     `protobuf:"varint,17,opt,name=valid,proto3" json:"valid,omitempty"`
	Error                string   `protobuf:"bytes,18,opt,name=error,proto3" json:"error,omitempty"`
	UserID               string   `protobuf:"bytes,27,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthUserResponse) Reset()         { *m = AuthUserResponse{} }
func (m *AuthUserResponse) String() string { return proto.CompactTextString(m) }
func (*AuthUserResponse) ProtoMessage()    {}
func (*AuthUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_504ce8545baed7b1, []int{5}
}

func (m *AuthUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthUserResponse.Unmarshal(m, b)
}
func (m *AuthUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthUserResponse.Marshal(b, m, deterministic)
}
func (m *AuthUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthUserResponse.Merge(m, src)
}
func (m *AuthUserResponse) XXX_Size() int {
	return xxx_messageInfo_AuthUserResponse.Size(m)
}
func (m *AuthUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthUserResponse proto.InternalMessageInfo

func (m *AuthUserResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *AuthUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *AuthUserResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

//UpdateUser Function
type UpdateUserRequest struct {
	UserID               string   `protobuf:"bytes,19,opt,name=userID,proto3" json:"userID,omitempty"`
	Field                string   `protobuf:"bytes,20,opt,name=field,proto3" json:"field,omitempty"`
	UpdatedValue         string   `protobuf:"bytes,21,opt,name=updatedValue,proto3" json:"updatedValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_504ce8545baed7b1, []int{6}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateUserRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *UpdateUserRequest) GetUpdatedValue() string {
	if m != nil {
		return m.UpdatedValue
	}
	return ""
}

type UpdateUserResponse struct {
	Error                string   `protobuf:"bytes,22,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_504ce8545baed7b1, []int{7}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

//DeleteUser Function
type DeleteUserRequest struct {
	UserID               string   `protobuf:"bytes,23,opt,name=userID,proto3" json:"userID,omitempty"`
	Username             string   `protobuf:"bytes,24,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,25,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_504ce8545baed7b1, []int{8}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *DeleteUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *DeleteUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type DeleteUserResponse struct {
	Error                string   `protobuf:"bytes,26,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_504ce8545baed7b1, []int{9}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*UserData)(nil), "UserData")
	proto.RegisterMapType((map[string]string)(nil), "UserData.DataEntry")
	proto.RegisterType((*AddUserResponse)(nil), "AddUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "GetUserRequest")
	proto.RegisterType((*GetUserByUsernameOrEmailRequest)(nil), "GetUserByUsernameOrEmailRequest")
	proto.RegisterType((*AuthUserRequest)(nil), "AuthUserRequest")
	proto.RegisterType((*AuthUserResponse)(nil), "AuthUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "DeleteUserResponse")
}

func init() { proto.RegisterFile("user-data-srv.proto", fileDescriptor_504ce8545baed7b1) }

var fileDescriptor_504ce8545baed7b1 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x93, 0xd2, 0x26, 0x53, 0x54, 0x3b, 0xe3, 0x52, 0x16, 0x73, 0x20, 0xda, 0x4b, 0xad,
	0x4a, 0x5d, 0x89, 0x72, 0x28, 0xe2, 0x82, 0x8a, 0x52, 0xa1, 0x1e, 0x10, 0x52, 0x50, 0x7b, 0x45,
	0x0b, 0x1e, 0x20, 0x22, 0x8d, 0xc3, 0xda, 0x0e, 0xca, 0x95, 0x6f, 0xe4, 0x83, 0xd0, 0xee, 0xda,
	0xf1, 0xda, 0x26, 0xea, 0xc5, 0xca, 0xcb, 0xcc, 0x9b, 0x37, 0x79, 0xf3, 0x1c, 0x08, 0x8b, 0x8c,
	0xd4, 0x79, 0x22, 0x73, 0x79, 0x9e, 0xa9, 0xb5, 0x58, 0xa9, 0x34, 0x4f, 0xf9, 0x1f, 0x0f, 0x86,
	0xb7, 0x19, 0xa9, 0xa9, 0xcc, 0x25, 0x9e, 0xc2, 0x9e, 0x2e, 0x33, 0x6f, 0x32, 0x88, 0x0f, 0x2f,
	0x42, 0x51, 0x15, 0x84, 0x7e, 0x5c, 0x2f, 0x73, 0xb5, 0x99, 0x99, 0x06, 0x3c, 0x86, 0x47, 0xa4,
	0x54, 0xaa, 0x58, 0x7f, 0xe2, 0xc5, 0xa3, 0x99, 0x05, 0xd1, 0x25, 0x8c, 0xb6, 0x8d, 0x18, 0xc0,
	0xe0, 0x27, 0x6d, 0x98, 0x67, 0x1a, 0xf4, 0x47, 0x4d, 0x5a, 0xcb, 0x45, 0x41, 0x15, 0xc9, 0x80,
	0x37, 0xfd, 0xd7, 0x1e, 0x7f, 0x0b, 0xfe, 0x55, 0x92, 0x68, 0xb5, 0x19, 0x65, 0xab, 0x74, 0x99,
	0x11, 0x9e, 0xc0, 0xbe, 0x5e, 0xf7, 0x66, 0xca, 0x06, 0xa6, 0xbb, 0x44, 0xb5, 0xf2, 0x9e, 0xa3,
	0xcc, 0x63, 0x38, 0x7a, 0x4f, 0xb9, 0x1d, 0xf0, 0xab, 0xa0, 0x2c, 0x77, 0xf8, 0x23, 0x97, 0xcf,
	0x3f, 0xc1, 0x8b, 0xb2, 0xf3, 0xdd, 0x46, 0x3f, 0x97, 0xf2, 0x9e, 0x3e, 0xaa, 0xeb, 0x7b, 0x39,
	0x5f, 0x54, 0xd4, 0x08, 0x86, 0x45, 0x59, 0x61, 0x60, 0xc8, 0x5b, 0x6c, 0xe4, 0x75, 0x2f, 0x3b,
	0x2c, 0xe5, 0x35, 0xe0, 0x9f, 0xc1, 0xbf, 0x2a, 0xf2, 0x1f, 0xae, 0xbe, 0x3b, 0xe4, 0x68, 0xd7,
	0x10, 0xdf, 0x19, 0xa2, 0x19, 0x2b, 0x99, 0x65, 0xbf, 0x53, 0x95, 0xb0, 0xc0, 0x32, 0x2a, 0xcc,
	0xef, 0x20, 0xa8, 0x05, 0x4a, 0x87, 0xac, 0x9d, 0xf3, 0x84, 0x8d, 0x27, 0x5e, 0x3c, 0x9c, 0x59,
	0x50, 0xfb, 0x83, 0x8e, 0x3f, 0x8e, 0x1b, 0xcf, 0x1b, 0x6e, 0x10, 0x8c, 0x6f, 0x57, 0x89, 0xcc,
	0xe9, 0xff, 0xd6, 0x85, 0x6d, 0xeb, 0xbf, 0xcd, 0x69, 0x91, 0xb0, 0x63, 0x3b, 0xda, 0x00, 0xe4,
	0xf0, 0xb8, 0x30, 0x23, 0x92, 0x3b, 0x73, 0xdc, 0x27, 0xa6, 0xd8, 0xf8, 0x8e, 0x9f, 0x01, 0xba,
	0x32, 0xf5, 0x0f, 0xb0, 0xab, 0x9e, 0xb8, 0xa7, 0xfc, 0x0a, 0xe3, 0x29, 0x2d, 0x68, 0xd7, 0x4a,
	0x4f, 0x1b, 0x2b, 0xb9, 0x2e, 0xb3, 0x96, 0xcb, 0xae, 0x9f, 0xcf, 0x5a, 0x7e, 0x9e, 0x01, 0xba,
	0x22, 0xed, 0x85, 0x22, 0x67, 0xa1, 0x8b, 0xbf, 0x7d, 0xf0, 0xab, 0x17, 0xe1, 0x83, 0x5c, 0xca,
	0xef, 0xa4, 0x30, 0x86, 0x83, 0x32, 0xb0, 0x38, 0xda, 0xbe, 0x25, 0x51, 0x20, 0x5a, 0x29, 0xe6,
	0x3d, 0x3c, 0x85, 0x83, 0x32, 0x6f, 0xe8, 0x8b, 0x66, 0x46, 0xa3, 0x9a, 0xca, 0x7b, 0x78, 0x03,
	0x6c, 0x57, 0x30, 0x71, 0x22, 0x1e, 0xc8, 0x6c, 0x73, 0xd4, 0x4b, 0x18, 0x56, 0x69, 0xc1, 0x40,
	0xb4, 0x92, 0x19, 0x8d, 0x45, 0x3b, 0x4a, 0xbc, 0x87, 0x97, 0x00, 0xf5, 0x85, 0x10, 0x45, 0x27,
	0x15, 0x51, 0x28, 0xba, 0x27, 0xb4, 0xc4, 0xda, 0x49, 0x44, 0xd1, 0xb9, 0x5d, 0x14, 0x8a, 0xae,
	0xd5, 0xbc, 0xf7, 0x65, 0xdf, 0xfc, 0xff, 0xbc, 0xfa, 0x17, 0x00, 0x00, 0xff, 0xff, 0x91, 0x50,
	0x15, 0xfb, 0x96, 0x04, 0x00, 0x00,
}
