// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jwt-srv.proto

package jwt_srv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserData struct {
	UserIdentity         string   `protobuf:"bytes,1,opt,name=userIdentity,proto3" json:"userIdentity,omitempty"`
	Scopes               []string `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_81325aed56fd2b61, []int{0}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetUserIdentity() string {
	if m != nil {
		return m.UserIdentity
	}
	return ""
}

func (m *UserData) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

type Token struct {
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Error                string   `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_81325aed56fd2b61, []int{1}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type AccessAndRefreshToken struct {
	AcccessToken         string   `protobuf:"bytes,4,opt,name=acccessToken,proto3" json:"acccessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,5,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	Error                string   `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessAndRefreshToken) Reset()         { *m = AccessAndRefreshToken{} }
func (m *AccessAndRefreshToken) String() string { return proto.CompactTextString(m) }
func (*AccessAndRefreshToken) ProtoMessage()    {}
func (*AccessAndRefreshToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_81325aed56fd2b61, []int{2}
}

func (m *AccessAndRefreshToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessAndRefreshToken.Unmarshal(m, b)
}
func (m *AccessAndRefreshToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessAndRefreshToken.Marshal(b, m, deterministic)
}
func (m *AccessAndRefreshToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessAndRefreshToken.Merge(m, src)
}
func (m *AccessAndRefreshToken) XXX_Size() int {
	return xxx_messageInfo_AccessAndRefreshToken.Size(m)
}
func (m *AccessAndRefreshToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessAndRefreshToken.DiscardUnknown(m)
}

var xxx_messageInfo_AccessAndRefreshToken proto.InternalMessageInfo

func (m *AccessAndRefreshToken) GetAcccessToken() string {
	if m != nil {
		return m.AcccessToken
	}
	return ""
}

func (m *AccessAndRefreshToken) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *AccessAndRefreshToken) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type TokenValid struct {
	Valid                bool     `protobuf:"varint,7,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenValid) Reset()         { *m = TokenValid{} }
func (m *TokenValid) String() string { return proto.CompactTextString(m) }
func (*TokenValid) ProtoMessage()    {}
func (*TokenValid) Descriptor() ([]byte, []int) {
	return fileDescriptor_81325aed56fd2b61, []int{3}
}

func (m *TokenValid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenValid.Unmarshal(m, b)
}
func (m *TokenValid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenValid.Marshal(b, m, deterministic)
}
func (m *TokenValid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenValid.Merge(m, src)
}
func (m *TokenValid) XXX_Size() int {
	return xxx_messageInfo_TokenValid.Size(m)
}
func (m *TokenValid) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenValid.DiscardUnknown(m)
}

var xxx_messageInfo_TokenValid proto.InternalMessageInfo

func (m *TokenValid) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type Claims struct {
	UserData             *UserData `protobuf:"bytes,8,opt,name=userData,proto3" json:"userData,omitempty"`
	CreationUTC          float64   `protobuf:"fixed64,9,opt,name=creationUTC,proto3" json:"creationUTC,omitempty"`
	ExpirationUTC        float64   `protobuf:"fixed64,10,opt,name=expirationUTC,proto3" json:"expirationUTC,omitempty"`
	Valid                bool      `protobuf:"varint,11,opt,name=valid,proto3" json:"valid,omitempty"`
	Error                string    `protobuf:"bytes,13,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Claims) Reset()         { *m = Claims{} }
func (m *Claims) String() string { return proto.CompactTextString(m) }
func (*Claims) ProtoMessage()    {}
func (*Claims) Descriptor() ([]byte, []int) {
	return fileDescriptor_81325aed56fd2b61, []int{4}
}

func (m *Claims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Claims.Unmarshal(m, b)
}
func (m *Claims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Claims.Marshal(b, m, deterministic)
}
func (m *Claims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Claims.Merge(m, src)
}
func (m *Claims) XXX_Size() int {
	return xxx_messageInfo_Claims.Size(m)
}
func (m *Claims) XXX_DiscardUnknown() {
	xxx_messageInfo_Claims.DiscardUnknown(m)
}

var xxx_messageInfo_Claims proto.InternalMessageInfo

func (m *Claims) GetUserData() *UserData {
	if m != nil {
		return m.UserData
	}
	return nil
}

func (m *Claims) GetCreationUTC() float64 {
	if m != nil {
		return m.CreationUTC
	}
	return 0
}

func (m *Claims) GetExpirationUTC() float64 {
	if m != nil {
		return m.ExpirationUTC
	}
	return 0
}

func (m *Claims) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Claims) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*UserData)(nil), "UserData")
	proto.RegisterType((*Token)(nil), "Token")
	proto.RegisterType((*AccessAndRefreshToken)(nil), "AccessAndRefreshToken")
	proto.RegisterType((*TokenValid)(nil), "TokenValid")
	proto.RegisterType((*Claims)(nil), "Claims")
}

func init() { proto.RegisterFile("jwt-srv.proto", fileDescriptor_81325aed56fd2b61) }

var fileDescriptor_81325aed56fd2b61 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xd1, 0x6a, 0xe2, 0x40,
	0x14, 0x35, 0xba, 0xc6, 0xe4, 0x6a, 0x5e, 0x86, 0x5d, 0x19, 0x16, 0x16, 0xc2, 0xb0, 0x0b, 0x79,
	0x31, 0xbb, 0xe8, 0x17, 0xb8, 0x8a, 0xa5, 0x85, 0x52, 0x08, 0xb1, 0x7d, 0x9e, 0x26, 0xb7, 0x6d,
	0x5a, 0x9b, 0xc8, 0xcc, 0x68, 0xdb, 0xef, 0xe9, 0x6b, 0x3f, 0xb2, 0x64, 0x62, 0xcc, 0x08, 0xd6,
	0xb7, 0x9c, 0x73, 0xcf, 0xb9, 0x73, 0xee, 0xbd, 0x01, 0xef, 0xf1, 0x45, 0x8d, 0xa4, 0xd8, 0x86,
	0x6b, 0x51, 0xa8, 0x82, 0x2d, 0xc0, 0x59, 0x4a, 0x14, 0x73, 0xae, 0x38, 0x61, 0x30, 0xd8, 0x48,
	0x14, 0xe7, 0x29, 0xe6, 0x2a, 0x53, 0x6f, 0xd4, 0xf2, 0xad, 0xc0, 0x8d, 0x0e, 0x38, 0x32, 0x04,
	0x5b, 0x26, 0xc5, 0x1a, 0x25, 0x6d, 0xfb, 0x9d, 0xc0, 0x8d, 0x76, 0x88, 0x4d, 0xa0, 0x1b, 0x17,
	0x4f, 0x98, 0x93, 0xef, 0xd0, 0x55, 0xe5, 0x07, 0xed, 0x68, 0x77, 0x05, 0x4a, 0x16, 0x85, 0x28,
	0x04, 0x1d, 0x54, 0xac, 0x06, 0x6c, 0x03, 0x3f, 0xa6, 0x49, 0x82, 0x52, 0x4e, 0xf3, 0x34, 0xc2,
	0x3b, 0x81, 0xf2, 0xa1, 0x6a, 0xc2, 0x60, 0xc0, 0x13, 0x5d, 0xd1, 0x98, 0x7e, 0xab, 0x92, 0x98,
	0x5c, 0xa9, 0x11, 0x86, 0x87, 0x76, 0x2b, 0x8d, 0xc9, 0x35, 0xcf, 0xda, 0xe6, 0xb3, 0x0c, 0x40,
	0x97, 0xaf, 0xf9, 0x2a, 0x4b, 0x4b, 0xcd, 0xb6, 0xfc, 0xa0, 0x3d, 0xdf, 0x0a, 0x9c, 0xa8, 0x02,
	0xec, 0xdd, 0x02, 0x7b, 0xb6, 0xe2, 0xd9, 0xb3, 0x24, 0x7f, 0xc0, 0xd9, 0xec, 0x56, 0x44, 0x1d,
	0xdf, 0x0a, 0xfa, 0x63, 0x37, 0xac, 0x77, 0x16, 0xed, 0x4b, 0xc4, 0x87, 0x7e, 0x22, 0x90, 0xab,
	0xac, 0xc8, 0x97, 0xf1, 0x8c, 0xba, 0xbe, 0x15, 0x58, 0x91, 0x49, 0x91, 0xdf, 0xe0, 0xe1, 0xeb,
	0x3a, 0x13, 0x7b, 0x0d, 0x68, 0xcd, 0x21, 0xd9, 0xe4, 0xe9, 0x1b, 0x79, 0x9a, 0x49, 0x3c, 0x63,
	0x92, 0xf1, 0x47, 0x1b, 0xe0, 0xe2, 0x26, 0xbe, 0xe4, 0x39, 0xbf, 0x47, 0x41, 0xfe, 0x02, 0x3d,
	0xc3, 0x1c, 0x05, 0x57, 0xb8, 0x28, 0x97, 0x30, 0x35, 0xd6, 0xd5, 0x64, 0xfe, 0x69, 0x87, 0x9a,
	0x62, 0x2d, 0x32, 0x87, 0x5f, 0xb5, 0xe1, 0xf8, 0x21, 0x0c, 0xd7, 0x30, 0x3c, 0x2a, 0x61, 0x2d,
	0x12, 0xc3, 0xbf, 0x93, 0x5d, 0xfe, 0x73, 0x89, 0xe9, 0x55, 0x7e, 0xd0, 0x78, 0x97, 0xe1, 0x44,
	0xd7, 0x11, 0x50, 0x7d, 0xa0, 0x63, 0xc3, 0xd4, 0xee, 0x5e, 0x58, 0xdd, 0x88, 0xb5, 0x08, 0x03,
	0xaf, 0x96, 0x7f, 0xa5, 0xb9, 0xb5, 0xf5, 0x3f, 0x3f, 0xf9, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xd6,
	0x74, 0x5e, 0x41, 0x04, 0x03, 0x00, 0x00,
}
