// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jwt-srv.proto

package jwt_srv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JWTData struct {
	UserIdentity         string   `protobuf:"bytes,1,opt,name=userIdentity,proto3" json:"userIdentity,omitempty"`
	Scopes               []string `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JWTData) Reset()         { *m = JWTData{} }
func (m *JWTData) String() string { return proto.CompactTextString(m) }
func (*JWTData) ProtoMessage()    {}
func (*JWTData) Descriptor() ([]byte, []int) {
	return fileDescriptor_81325aed56fd2b61, []int{0}
}

func (m *JWTData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTData.Unmarshal(m, b)
}
func (m *JWTData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTData.Marshal(b, m, deterministic)
}
func (m *JWTData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTData.Merge(m, src)
}
func (m *JWTData) XXX_Size() int {
	return xxx_messageInfo_JWTData.Size(m)
}
func (m *JWTData) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTData.DiscardUnknown(m)
}

var xxx_messageInfo_JWTData proto.InternalMessageInfo

func (m *JWTData) GetUserIdentity() string {
	if m != nil {
		return m.UserIdentity
	}
	return ""
}

func (m *JWTData) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TokenType            string   `protobuf:"bytes,2,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_81325aed56fd2b61, []int{1}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *Token) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AccessAndRefreshToken struct {
	AcccessToken         string   `protobuf:"bytes,1,opt,name=acccessToken,proto3" json:"acccessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessAndRefreshToken) Reset()         { *m = AccessAndRefreshToken{} }
func (m *AccessAndRefreshToken) String() string { return proto.CompactTextString(m) }
func (*AccessAndRefreshToken) ProtoMessage()    {}
func (*AccessAndRefreshToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_81325aed56fd2b61, []int{2}
}

func (m *AccessAndRefreshToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessAndRefreshToken.Unmarshal(m, b)
}
func (m *AccessAndRefreshToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessAndRefreshToken.Marshal(b, m, deterministic)
}
func (m *AccessAndRefreshToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessAndRefreshToken.Merge(m, src)
}
func (m *AccessAndRefreshToken) XXX_Size() int {
	return xxx_messageInfo_AccessAndRefreshToken.Size(m)
}
func (m *AccessAndRefreshToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessAndRefreshToken.DiscardUnknown(m)
}

var xxx_messageInfo_AccessAndRefreshToken proto.InternalMessageInfo

func (m *AccessAndRefreshToken) GetAcccessToken() string {
	if m != nil {
		return m.AcccessToken
	}
	return ""
}

func (m *AccessAndRefreshToken) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *AccessAndRefreshToken) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TokenValid struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenValid) Reset()         { *m = TokenValid{} }
func (m *TokenValid) String() string { return proto.CompactTextString(m) }
func (*TokenValid) ProtoMessage()    {}
func (*TokenValid) Descriptor() ([]byte, []int) {
	return fileDescriptor_81325aed56fd2b61, []int{3}
}

func (m *TokenValid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenValid.Unmarshal(m, b)
}
func (m *TokenValid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenValid.Marshal(b, m, deterministic)
}
func (m *TokenValid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenValid.Merge(m, src)
}
func (m *TokenValid) XXX_Size() int {
	return xxx_messageInfo_TokenValid.Size(m)
}
func (m *TokenValid) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenValid.DiscardUnknown(m)
}

var xxx_messageInfo_TokenValid proto.InternalMessageInfo

func (m *TokenValid) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type Claims struct {
	UserIdentity         string   `protobuf:"bytes,1,opt,name=userIdentity,proto3" json:"userIdentity,omitempty"`
	Scopes               []string `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	IsFresh              bool     `protobuf:"varint,3,opt,name=isFresh,proto3" json:"isFresh,omitempty"`
	IsRefresh            bool     `protobuf:"varint,4,opt,name=isRefresh,proto3" json:"isRefresh,omitempty"`
	CreationUTC          int64    `protobuf:"varint,5,opt,name=creationUTC,proto3" json:"creationUTC,omitempty"`
	ExpirationUTC        int64    `protobuf:"varint,6,opt,name=expirationUTC,proto3" json:"expirationUTC,omitempty"`
	Message              string   `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Valid                bool     `protobuf:"varint,8,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Claims) Reset()         { *m = Claims{} }
func (m *Claims) String() string { return proto.CompactTextString(m) }
func (*Claims) ProtoMessage()    {}
func (*Claims) Descriptor() ([]byte, []int) {
	return fileDescriptor_81325aed56fd2b61, []int{4}
}

func (m *Claims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Claims.Unmarshal(m, b)
}
func (m *Claims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Claims.Marshal(b, m, deterministic)
}
func (m *Claims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Claims.Merge(m, src)
}
func (m *Claims) XXX_Size() int {
	return xxx_messageInfo_Claims.Size(m)
}
func (m *Claims) XXX_DiscardUnknown() {
	xxx_messageInfo_Claims.DiscardUnknown(m)
}

var xxx_messageInfo_Claims proto.InternalMessageInfo

func (m *Claims) GetUserIdentity() string {
	if m != nil {
		return m.UserIdentity
	}
	return ""
}

func (m *Claims) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *Claims) GetIsFresh() bool {
	if m != nil {
		return m.IsFresh
	}
	return false
}

func (m *Claims) GetIsRefresh() bool {
	if m != nil {
		return m.IsRefresh
	}
	return false
}

func (m *Claims) GetCreationUTC() int64 {
	if m != nil {
		return m.CreationUTC
	}
	return 0
}

func (m *Claims) GetExpirationUTC() int64 {
	if m != nil {
		return m.ExpirationUTC
	}
	return 0
}

func (m *Claims) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Claims) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*JWTData)(nil), "JWTData")
	proto.RegisterType((*Token)(nil), "Token")
	proto.RegisterType((*AccessAndRefreshToken)(nil), "AccessAndRefreshToken")
	proto.RegisterType((*TokenValid)(nil), "TokenValid")
	proto.RegisterType((*Claims)(nil), "Claims")
}

func init() { proto.RegisterFile("jwt-srv.proto", fileDescriptor_81325aed56fd2b61) }

var fileDescriptor_81325aed56fd2b61 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0xa5, 0x54, 0xda, 0x32, 0xd2, 0xcb, 0x46, 0x49, 0x63, 0x3c, 0x34, 0x1b, 0x0f, 0x5c, 0x6c,
	0xa2, 0x5e, 0xbd, 0x10, 0x94, 0x44, 0x8e, 0x4d, 0x91, 0xf3, 0x5a, 0x56, 0x5d, 0x85, 0xb6, 0xd9,
	0x59, 0x51, 0xfe, 0xcd, 0xcf, 0xf2, 0x03, 0xcc, 0x6e, 0x8b, 0x6d, 0x13, 0xc2, 0xc5, 0xdb, 0xcc,
	0x9b, 0x37, 0xfb, 0x66, 0xde, 0x2c, 0xf8, 0x6f, 0x9f, 0xea, 0x12, 0xe5, 0x26, 0x2a, 0x64, 0xae,
	0x72, 0x7a, 0x0f, 0xee, 0x6c, 0x91, 0xdc, 0x31, 0xc5, 0x08, 0x85, 0xc1, 0x07, 0x72, 0xf9, 0xb0,
	0xe4, 0x99, 0x12, 0x6a, 0x1b, 0x58, 0xa1, 0x35, 0xea, 0xc7, 0x2d, 0x8c, 0x0c, 0xc1, 0xc1, 0x34,
	0x2f, 0x38, 0x06, 0xdd, 0xd0, 0x1e, 0xf5, 0xe3, 0x2a, 0xa3, 0x73, 0xe8, 0x25, 0xf9, 0x3b, 0xcf,
	0xc8, 0x09, 0xf4, 0x94, 0x0e, 0xaa, 0xee, 0x32, 0x21, 0xe7, 0xd0, 0x37, 0x41, 0xb2, 0x2d, 0x78,
	0xd0, 0x35, 0x95, 0x1a, 0x20, 0x01, 0xb8, 0x6b, 0x8e, 0xc8, 0x5e, 0x78, 0x60, 0x9b, 0xda, 0x2e,
	0xa5, 0x5b, 0x38, 0x1d, 0xa7, 0x29, 0x47, 0x1c, 0x67, 0xcb, 0x98, 0x3f, 0x4b, 0x8e, 0xaf, 0xa5,
	0x0c, 0x85, 0x01, 0x4b, 0x4d, 0x25, 0x69, 0xa8, 0xb5, 0x30, 0xcd, 0x91, 0x8d, 0x9e, 0x4a, 0xb7,
	0x85, 0x1d, 0x90, 0xa6, 0x00, 0x86, 0xf2, 0xc8, 0x56, 0x62, 0xa9, 0xd7, 0xda, 0xe8, 0xc0, 0x08,
	0x79, 0x71, 0x99, 0xd0, 0x1f, 0x0b, 0x9c, 0xc9, 0x8a, 0x89, 0x35, 0xfe, 0xc7, 0x3c, 0x3d, 0x84,
	0xc0, 0xa9, 0x1e, 0xca, 0x0c, 0xe1, 0xc5, 0xbb, 0x54, 0xfb, 0x26, 0xb0, 0x5a, 0x3c, 0x38, 0x32,
	0xb5, 0x1a, 0x20, 0x21, 0x1c, 0xa7, 0x92, 0x33, 0x25, 0xf2, 0x6c, 0x9e, 0x4c, 0x82, 0x5e, 0x68,
	0x8d, 0xec, 0xb8, 0x09, 0x91, 0x0b, 0xf0, 0xf9, 0x57, 0x21, 0xe4, 0x1f, 0xc7, 0x31, 0x9c, 0x36,
	0xd8, 0x34, 0xc1, 0x6d, 0x99, 0x50, 0xaf, 0xed, 0x35, 0xd6, 0xbe, 0xfe, 0xb6, 0xc0, 0x9e, 0x2d,
	0x12, 0x12, 0x02, 0x4c, 0x6b, 0x2b, 0xbd, 0xa8, 0xfa, 0x48, 0x67, 0x4e, 0x64, 0x10, 0xda, 0x21,
	0xb7, 0x30, 0xdc, 0x7b, 0x3f, 0x6c, 0xb0, 0x87, 0xd1, 0x5e, 0x0a, 0xed, 0x90, 0x2b, 0xf0, 0xdb,
	0x4d, 0xd5, 0xc3, 0x07, 0x5a, 0x28, 0xf8, 0xe6, 0x60, 0x4c, 0xf1, 0x72, 0xaa, 0x5d, 0x8b, 0x1b,
	0x95, 0x87, 0xa2, 0x9d, 0x27, 0xc7, 0xfc, 0xfc, 0x9b, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21,
	0x79, 0xb6, 0x12, 0x0a, 0x03, 0x00, 0x00,
}
