// Code generated by protoc-gen-go. DO NOT EDIT.
// source: email-verification-srv.proto

package email_verification_srv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendVerificationRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendVerificationRequest) Reset()         { *m = SendVerificationRequest{} }
func (m *SendVerificationRequest) String() string { return proto.CompactTextString(m) }
func (*SendVerificationRequest) ProtoMessage()    {}
func (*SendVerificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaa78945219572d2, []int{0}
}

func (m *SendVerificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendVerificationRequest.Unmarshal(m, b)
}
func (m *SendVerificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendVerificationRequest.Marshal(b, m, deterministic)
}
func (m *SendVerificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendVerificationRequest.Merge(m, src)
}
func (m *SendVerificationRequest) XXX_Size() int {
	return xxx_messageInfo_SendVerificationRequest.Size(m)
}
func (m *SendVerificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendVerificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendVerificationRequest proto.InternalMessageInfo

func (m *SendVerificationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SendVerificationResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendVerificationResponse) Reset()         { *m = SendVerificationResponse{} }
func (m *SendVerificationResponse) String() string { return proto.CompactTextString(m) }
func (*SendVerificationResponse) ProtoMessage()    {}
func (*SendVerificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaa78945219572d2, []int{1}
}

func (m *SendVerificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendVerificationResponse.Unmarshal(m, b)
}
func (m *SendVerificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendVerificationResponse.Marshal(b, m, deterministic)
}
func (m *SendVerificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendVerificationResponse.Merge(m, src)
}
func (m *SendVerificationResponse) XXX_Size() int {
	return xxx_messageInfo_SendVerificationResponse.Size(m)
}
func (m *SendVerificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendVerificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendVerificationResponse proto.InternalMessageInfo

func (m *SendVerificationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type VerifyRequest struct {
	VerificationCode     string   `protobuf:"bytes,1,opt,name=verificationCode,proto3" json:"verificationCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaa78945219572d2, []int{2}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

type VerifyResponse struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyResponse) Reset()         { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()    {}
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaa78945219572d2, []int{3}
}

func (m *VerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResponse.Unmarshal(m, b)
}
func (m *VerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResponse.Marshal(b, m, deterministic)
}
func (m *VerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResponse.Merge(m, src)
}
func (m *VerifyResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyResponse.Size(m)
}
func (m *VerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResponse proto.InternalMessageInfo

func (m *VerifyResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*SendVerificationRequest)(nil), "SendVerificationRequest")
	proto.RegisterType((*SendVerificationResponse)(nil), "SendVerificationResponse")
	proto.RegisterType((*VerifyRequest)(nil), "VerifyRequest")
	proto.RegisterType((*VerifyResponse)(nil), "VerifyResponse")
}

func init() { proto.RegisterFile("email-verification-srv.proto", fileDescriptor_aaa78945219572d2) }

var fileDescriptor_aaa78945219572d2 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0xcd, 0x4d, 0xcc,
	0xcc, 0xd1, 0x2d, 0x4b, 0x2d, 0xca, 0x4c, 0xcb, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2d,
	0x2e, 0x2a, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe7, 0x12, 0x0f, 0x4e, 0xcd, 0x4b,
	0x09, 0x43, 0x92, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe1, 0x62, 0x05, 0x6b,
	0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x94, 0x4c, 0xb8, 0x24, 0x30, 0x35, 0x14,
	0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x49, 0x70, 0xb1, 0xe7, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7,
	0x42, 0xf5, 0xc0, 0xb8, 0x4a, 0xd6, 0x5c, 0xbc, 0x60, 0x1d, 0x95, 0x30, 0xc3, 0xb5, 0xb8, 0x04,
	0x90, 0x5d, 0xe4, 0x9c, 0x9f, 0x02, 0xd3, 0x83, 0x21, 0xae, 0xa4, 0xc6, 0xc5, 0x07, 0xd3, 0x0c,
	0xb5, 0x08, 0xab, 0xd3, 0x8c, 0xba, 0x19, 0xb9, 0x04, 0x5d, 0x41, 0x2c, 0x64, 0xc7, 0x09, 0x79,
	0x72, 0x09, 0xa0, 0x3b, 0x58, 0x48, 0x42, 0x0f, 0x87, 0xa7, 0xa5, 0x24, 0xf5, 0x70, 0xf9, 0x4e,
	0x89, 0x41, 0x48, 0x9b, 0x8b, 0x0d, 0xe2, 0x10, 0x21, 0x3e, 0x3d, 0x14, 0xef, 0x48, 0xf1, 0xeb,
	0xa1, 0xba, 0x50, 0x89, 0x21, 0x89, 0x0d, 0x1c, 0xc0, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x5c, 0x0a, 0xb2, 0x97, 0x80, 0x01, 0x00, 0x00,
}
