// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: jwt-srv.proto

package jwt_srv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for JWT service

type JWTService interface {
	FreshToken(ctx context.Context, in *JWTData, opts ...client.CallOption) (*Token, error)
	AccessAndRefreshTokens(ctx context.Context, in *JWTData, opts ...client.CallOption) (*AccessAndRefreshToken, error)
	RefreshTokens(ctx context.Context, in *Token, opts ...client.CallOption) (*AccessAndRefreshToken, error)
	ValidateToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Claims, error)
}

type jWTService struct {
	c    client.Client
	name string
}

func NewJWTService(name string, c client.Client) JWTService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "jwt"
	}
	return &jWTService{
		c:    c,
		name: name,
	}
}

func (c *jWTService) FreshToken(ctx context.Context, in *JWTData, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.name, "JWT.FreshToken", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jWTService) AccessAndRefreshTokens(ctx context.Context, in *JWTData, opts ...client.CallOption) (*AccessAndRefreshToken, error) {
	req := c.c.NewRequest(c.name, "JWT.AccessAndRefreshTokens", in)
	out := new(AccessAndRefreshToken)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jWTService) RefreshTokens(ctx context.Context, in *Token, opts ...client.CallOption) (*AccessAndRefreshToken, error) {
	req := c.c.NewRequest(c.name, "JWT.RefreshTokens", in)
	out := new(AccessAndRefreshToken)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jWTService) ValidateToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Claims, error) {
	req := c.c.NewRequest(c.name, "JWT.ValidateToken", in)
	out := new(Claims)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for JWT service

type JWTHandler interface {
	FreshToken(context.Context, *JWTData, *Token) error
	AccessAndRefreshTokens(context.Context, *JWTData, *AccessAndRefreshToken) error
	RefreshTokens(context.Context, *Token, *AccessAndRefreshToken) error
	ValidateToken(context.Context, *Token, *Claims) error
}

func RegisterJWTHandler(s server.Server, hdlr JWTHandler, opts ...server.HandlerOption) error {
	type jWT interface {
		FreshToken(ctx context.Context, in *JWTData, out *Token) error
		AccessAndRefreshTokens(ctx context.Context, in *JWTData, out *AccessAndRefreshToken) error
		RefreshTokens(ctx context.Context, in *Token, out *AccessAndRefreshToken) error
		ValidateToken(ctx context.Context, in *Token, out *Claims) error
	}
	type JWT struct {
		jWT
	}
	h := &jWTHandler{hdlr}
	return s.Handle(s.NewHandler(&JWT{h}, opts...))
}

type jWTHandler struct {
	JWTHandler
}

func (h *jWTHandler) FreshToken(ctx context.Context, in *JWTData, out *Token) error {
	return h.JWTHandler.FreshToken(ctx, in, out)
}

func (h *jWTHandler) AccessAndRefreshTokens(ctx context.Context, in *JWTData, out *AccessAndRefreshToken) error {
	return h.JWTHandler.AccessAndRefreshTokens(ctx, in, out)
}

func (h *jWTHandler) RefreshTokens(ctx context.Context, in *Token, out *AccessAndRefreshToken) error {
	return h.JWTHandler.RefreshTokens(ctx, in, out)
}

func (h *jWTHandler) ValidateToken(ctx context.Context, in *Token, out *Claims) error {
	return h.JWTHandler.ValidateToken(ctx, in, out)
}
